[build]
builder = "docker"

[[services]]
  build = { dockerfile = "./SimpleApi/Dockerfile" }
  ports = ["5000"]
  env = ["ASPNETCORE_URLS=http://+:80"]
  [services.start]
    cmd = "dotnet SimpleApi.dll"

[[services]]
  build = { dockerfile = "./frontend/Dockerfile" }
  ports = ["8080"]
  [services.start]
    cmd = "nginx -g 'daemon off;'"