[build]
builder = "docker"  # Pastikan nilai ini adalah "docker" karena Anda menggunakan Dockerfile

[[services]]
  build = { dockerfile = "./SimpleApi/Dockerfile" }
  ports = ["80"]
  env = ["ASPNETCORE_URLS=http://+:80"]
  [services.start]
    cmd = "dotnet SimpleApi.dll"

[[services]]
  build = { dockerfile = "./frontend/Dockerfile" }
  ports = ["80"]
  [services.start]
    cmd = "nginx -g 'daemon off;'"